### ISSUE TITLE
Link to article about nixops is broken.

### ISSUE THREAD

**Issue by yisraeldov** [mrVanDalo/tech.ingolf-wagner.de#1]
https://github.com/mrVanDalo/tech.ingolf-wagner.de/blob/ee838cbd393cf92b9f3516f94c61ced4481fc872/articles/nixos/krops.markdown?plain=1#L24

**Comment by mrVanDalo** [comment]
Thank you, will take care of it in a few days. Don't have time at the moment.

**Comment by mrVanDalo** [comment]
Thank you @yisraeldov I'll use a wayback Machine link. But I also realized this is not the repo for my website. But thank you. I want to check links automatically, but had not the time yet to implement that.
